# Generated by Django 4.1.1 on 2022-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extintor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.CharField(max_length=50)),
                ('fecha_ultima_mantencion', models.DateField()),
                ('fecha_sig_mantencion', models.DateField()),
            ],
        ),
    ]
